/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async rewrites() {
    return [
      // sitemap/robots are generated by the Express app (mounted at /api)
      { source: "/sitemap.xml", destination: "/api/sitemap.xml" },
      { source: "/robots.txt", destination: "/api/robots.txt" },
    ];
  },
};

export default nextConfig;
